### ISSUE TITLE
Publish v0.1.5

### ISSUE THREAD

**Issue by ritiek** [enricobacis/lyricwikia#5]
I'd love to use your library in [spotify-downloader](https://github.com/ritiek/spotify-downloader). It would be nice to install lyricwikia and included changes in e6b40277582adf0414fb54c1c79f1b697838ba41 directly from pypi, so that it is easier to deal with *LyricsNotFound* exception.

It's okay if you cannot due to some reason, I won't mind at all. I don't want to create any unnecessary stress on your side. :smile:

Thank you so much!

**Comment by enricobacis** [comment]
Cool project! I've updated the library and added some test, it's now at version 0.1.8, let me know when you have integrated in into spotify-downloader, so that I can add a section in the README to list the projects that are using this library.

**Comment by ritiek** [comment]
That was quick! Amazing.

> let me know when you have integrated in into spotify-downloader, so that I can add a section in the README to list the projects that are using this library.

Yep, sure!

Thanks once again!

**Comment by ritiek** [comment]
Okay, I've integrated lyricwikia as of ritiek/spotify-downloader#194.

**Comment by enricobacis** [comment]
Nice, I've updated the readme of this project.
