### ISSUE TITLE
I just added the package to the AUR

### ISSUE THREAD

**Issue by marioortizmanero** [enricobacis/lyricwikia#6]
Just wanted to let you know that I uploaded this to the AUR - https://aur.archlinux.org/packages/python-lyricwikia/ so that I could use it for my own project: [spotify-music-videos](https://github.com/marioortizmanero/spotify-music-videos). Also, I can let you co-maintain it if you want. You can add that to the README if you want :)

**Comment by enricobacis** [comment]
Hey, thanks for that! Can you submit a PR to the README to add a link to both the AUR and your project?

**Comment by marioortizmanero** [comment]
Done. I hope I didn't mess anything up, I had never used the rst markup.
