### ISSUE TITLE
Move to Python3!

### ISSUE THREAD

**Issue by bodasadallah** [enricobacis/lyricwikia#9]
I tried to use this , but I faced lot of problems due to that this package still runs on python 2

**Comment by enricobacis** [comment]
Hi,

Could you please specify the kind of problems that you get?

The code is written to be compatible with both python2 and python3 (it even uses `six` for increased compatibility). Travis CI is even running (small) tests for this package on both python2.7 and python3.6 and they are passing.

Please attach the stack trace or provide more details about the errors when you open issues.

**Comment by enricobacis** [comment]
Closing this due to no reply. Feel free to reopen this is the problem still occurs.

**Comment by bodasadallah** [comment]
I got errors in the print functions, and couldn't compile the code

**Comment by enricobacis** [comment]
As you can see here:

https://github.com/enricobacis/lyricwikia/search?q=print&unscoped_q=print

there is a single use of the `print` function in the whole code and is python3 compatible, so I think that the error is in your part of the code.
